In [169]:
import pandas as pd
#Loading data
df = pd.read_csv('Titanic-Dataset.csv')

## Exploration
Loading and exploring the Titanic dataset to understand its structure, 
shape, and data types before cleaning.

In [170]:
#exploration
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [171]:
print(f"Shape: {df.shape}")

Shape: (891, 12)

In [172]:
print(f"Column names: {df.columns}")

Column names: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [173]:
print(f"Column datatypes:\n{df.dtypes}")

Column datatypes:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [174]:
print(f"Summary stats:\n{df.describe()}")

Summary stats:
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [175]:
print(f"Null values in entire dataset: {df.isnull().sum().sum()}")

Null values in entire dataset: 866

In [176]:
print(f"Null values per column:\n{df.isnull().sum()}")

Null values per column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [177]:
print(f"Uniqur value in sex column: {df['Sex'].unique()}\nUnique values in Embarkes column: {df['Embarked'].unique()}")

Uniqur value in sex column: ['male' 'female']
Unique values in Embarkes column: ['S' 'C' 'Q' nan]

In [179]:
df[['Name','Age','Survived']]

                                                  Name   Age  Survived
0                              Braund, Mr. Owen Harris  22.0         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                               Heikkinen, Miss. Laina  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                             Allen, Mr. William Henry  35.0         0
..                                                 ...   ...       ...
886                              Montvila, Rev. Juozas  27.0         0
887                       Graham, Miss. Margaret Edith  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN         0
889                              Behr, Mr. Karl Howell  26.0         1
890                                Dooley, Mr. Patrick  32.0         0

[891 rows x 3 columns]

In [180]:
#passengers who survived
df[df['Survived']==1][['Name', 'Survived']]

                                                  Name  Survived
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                               Heikkinen, Miss. Laina         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         1
9                  Nasser, Mrs. Nicholas (Adele Achem)         1
..                                                 ...       ...
875                   Najib, Miss. Adele Kiamie "Jane"         1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)         1
880       Shelley, Mrs. William (Imanita Parrish Hall)         1
887                       Graham, Miss. Margaret Edith         1
889                              Behr, Mr. Karl Howell         1

[342 rows x 2 columns]

In [181]:
#female passengers over 30
df[(df['Sex'] == 'female') & (df['Age'] > 30)][['Name','Age','Sex']]

                                                  Name   Age     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
11                            Bonnell, Miss. Elizabeth  58.0  female
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0  female
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0  female
..                                                 ...   ...     ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0  female
865                           Bystrom, Mrs. (Karolina)  42.0  female
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0  female
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0  female
885               Rice, Mrs. William (Margaret Norton)  39.0  female

[103 rows x 3 columns]

In [182]:
#passengers of pclass 1 or 2
df[df['Pclass'].isin([1,2])][['Name','Pclass']]

                                                  Name  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
6                              McCarthy, Mr. Timothy J       1
9                  Nasser, Mrs. Nicholas (Adele Achem)       2
11                            Bonnell, Miss. Elizabeth       1
..                                                 ...     ...
880       Shelley, Mrs. William (Imanita Parrish Hall)       2
883                      Banfield, Mr. Frederick James       2
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
889                              Behr, Mr. Karl Howell       1

[400 rows x 2 columns]

In [183]:
#passengers where age is not null
df[df['Age'].notna()][['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
885               Rice, Mrs. William (Margaret Norton)  39.0
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[714 rows x 2 columns]

In [184]:
#first 5 rows anmd 3 cols 
df.iloc[0:5,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

## Data Cleaning
Handling missing values in Age (filled with median) and Embarked 
(filled with mode). Dropping Cabin due to 77% missing values.

In [186]:
#filling missing age with median
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'].isna().sum()

np.int64(0)

In [187]:
#filling embarked with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Embarked'].isna().sum()

np.int64(0)

In [188]:
#dropped col
df = df.drop(columns='Cabin')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [189]:
#checking for nulls
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [190]:
df.drop_duplicates()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [191]:
#encoding
df['Sex'] = df['Sex'].map({'male': 0, 'female':1})
df['Sex'].unique()

array([0, 1])

In [192]:
#confirming datatypes 
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [193]:
#fixing dtypes
df['Age'] = df['Age'].astype(int)

In [194]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [195]:
df['Embarked'] = df['Embarked'].map({'S': 0,'C': 1,'Q': 2})
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex              int64
Age              int64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked         int64
dtype: object

In [196]:
#leaving name and ticket as it is for now may drop them later on

In [197]:
#Feature engineering

In [198]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df[['FamilySize', 'SibSp', 'Parch']]

     FamilySize  SibSp  Parch
0             2      1      0
1             2      1      0
2             1      0      0
3             2      1      0
4             1      0      0
..          ...    ...    ...
886           1      0      0
887           1      0      0
888           4      1      2
889           1      0      0
890           1      0      0

[891 rows x 3 columns]

In [199]:
def func(size):
    if size == 1:
        return 1
    else:
        return 0
df['IsAlone'] = df['FamilySize'].apply(func)
df[['IsAlone','FamilySize']]

     IsAlone  FamilySize
0          0           2
1          0           2
2          1           1
3          0           2
4          1           1
..       ...         ...
886        1           1
887        1           1
888        0           4
889        1           1
890        1           1

[891 rows x 2 columns]

In [200]:
df['AgeGroup'] = df['Age'].apply(lambda x: 'child' if x  < 18  else 'adult' if x < 60 else 'senior')
df[['Age','AgeGroup']]

     Age AgeGroup
0     22    adult
1     38    adult
2     26    adult
3     35    adult
4     35    adult
..   ...      ...
886   27    adult
887   19    adult
888   28    adult
889   26    adult
890   32    adult

[891 rows x 2 columns]

In [201]:
df['FarePerPerson'] = df['Fare']/df['FamilySize']
df[['Fare','FarePerPerson','FamilySize']]

        Fare  FarePerPerson  FamilySize
0     7.2500        3.62500           2
1    71.2833       35.64165           2
2     7.9250        7.92500           1
3    53.1000       26.55000           2
4     8.0500        8.05000           1
..       ...            ...         ...
886  13.0000       13.00000           1
887  30.0000       30.00000           1
888  23.4500        5.86250           4
889  30.0000       30.00000           1
890   7.7500        7.75000           1

[891 rows x 3 columns]

In [202]:
df['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)
df[['Name','Title']]

                                                  Name Title
0                              Braund, Mr. Owen Harris    Mr
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
2                               Heikkinen, Miss. Laina  Miss
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
4                             Allen, Mr. William Henry    Mr
..                                                 ...   ...
886                              Montvila, Rev. Juozas   Rev
887                       Graham, Miss. Margaret Edith  Miss
888           Johnston, Miss. Catherine Helen "Carrie"  Miss
889                              Behr, Mr. Karl Howell    Mr
890                                Dooley, Mr. Patrick    Mr

[891 rows x 2 columns]

## aggregation

In [204]:
#survival rate by sex
rate = df.groupby('Sex')['Survived'].mean()
if rate[0] > rate[1]:
    print(f'Survival rate of men was greater')
elif rate[1] > rate[0]:
    print(f'Survival rate of women was greater')
else:
    print(f'Survival rate was equal')

Survival rate of women was greater

In [205]:
#survival rate by p class
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [206]:
#avg age by pclass
df.groupby('Pclass')['Age'].mean()

Pclass
1    36.805556
2    29.744565
3    25.914460
Name: Age, dtype: float64

In [207]:
df.groupby(['Pclass','Sex'])['Age'].mean()

Pclass  Sex
1       0      38.983607
        1      33.978723
2       0      30.481481
        1      28.697368
3       0      26.893372
        1      23.555556
Name: Age, dtype: float64

In [208]:
df.groupby('AgeGroup').size()

AgeGroup
adult     752
child     113
senior     26
dtype: int64

In [209]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [210]:
df.groupby('IsAlone')['Survived'].mean()

IsAlone
0    0.505650
1    0.303538
Name: Survived, dtype: float64

## sorting and final analysis

In [211]:

df.sort_values(by = 'Age', ascending = False)['Age']

630    80
851    74
96     71
493    71
672    70
       ..
78      0
469     0
644     0
831     0
755     0
Name: Age, Length: 891, dtype: int64

In [217]:
sorted_fare = df.sort_values(by = 'Fare', ascending = False)
sorted_fare.iloc[0]

PassengerId                   259
Survived                        1
Pclass                          1
Name             Ward, Miss. Anna
Sex                             1
Age                            35
SibSp                           0
Parch                           0
Ticket                   PC 17755
Fare                     512.3292
Embarked                        1
FamilySize                      1
IsAlone                         1
AgeGroup                    adult
FarePerPerson            512.3292
Title                        Miss
Name: 258, dtype: object

In [220]:
sorted_fare.head()['Ticket']

258    PC 17755
737    PC 17755
679    PC 17755
88        19950
27        19950
Name: Ticket, dtype: object

In [221]:
df[(df['Title'] == 'Mr') & (df['Survived']==0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,IsAlone,AgeGroup,FarePerPerson,Title
0,1,0,3,"Braund, Mr. Owen Harris",0,22,1,0,A/5 21171,7.2500,0,2,0,adult,3.6250,Mr
4,5,0,3,"Allen, Mr. William Henry",0,35,0,0,373450,8.0500,0,1,1,adult,8.0500,Mr
5,6,0,3,"Moran, Mr. James",0,28,0,0,330877,8.4583,2,1,1,adult,8.4583,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",0,54,0,0,17463,51.8625,0,1,1,adult,51.8625,Mr
12,13,0,3,"Saundercock, Mr. William Henry",0,20,0,0,A/5. 2151,8.0500,0,1,1,adult,8.0500,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,879,0,3,"Laleff, Mr. Kristo",0,28,0,0,349217,7.8958,0,1,1,adult,7.8958,Mr
881,882,0,3,"Markun, Mr. Johann",0,33,0,0,349257,7.8958,0,1,1,adult,7.8958,Mr
883,884,0,2,"Banfield, Mr. Frederick James",0,28,0,0,C.A./SOTON 34068,10.5000,0,1,1,adult,10.5000,Mr
884,885,0,3,"Sutehall, Mr. Henry Jr",0,25,0,0,SOTON/OQ 392076,7.0500,0,1,1,adult,7.0500,Mr
890,891,0,3,"Dooley, Mr. Patrick",0,32,0,0,370376,7.7500,2,1,1,adult,7.7500,Mr

In [232]:
survived_child = len(df[(df['AgeGroup']=='child')&(df['Survived']==1)])
total_child =  len(df[(df['AgeGroup']=='child')])
perc = (survived_child/total_child)*100
print(f"{perc}")

53.98230088495575